baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Website Clone'

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'

[params]
  description = "Professional business solutions and services"
  logo = "/logo.svg"
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true